name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  checks: write

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Cache Build files
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('gradle.properties') }}-v2

      - uses: gradle/actions/setup-gradle@v4
      - name: Run Integration Tests
        run: ./gradlew integration-tests:test

      - name: Archive Reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: reports
          path: '**/build/reports/*'

      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@v5
        if: ${{ always() }}
        with:
          report_paths: '**/TEST-*.xml'
